/*
 * Copyright 2025 Calin-Andrei Burloiu
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

package org.calinburloiu.music.scmidi

import org.calinburloiu.music.microtonalist.common.concurrency.Locking

import java.util.concurrent.locks.{ReadWriteLock, ReentrantReadWriteLock}
import javax.sound.midi.{MidiMessage, Receiver, Transmitter}

/**
 * MIDI interceptor that can change MIDI events that pass through it.
 *
 * Its input is handled by its [[receiver]] and its output by its [[transmitter]]. The MIDI messages can be filtered,
 * changes or new message can be generated by implementing the [[MidiProcessor#process()]] method.
 *
 * It can only be used after a receiver is set for its [[transmitter]] when it is said that it ''connects''. When
 * this happens [[MidiProcessor#onConnect()]] callback is called. When the receiver is changed, it first 
 * _disconnects_, so [[MidiProcessor#onDisconnect()]] is called before. Similarly, [[MidiProcessor#onDisconnect()]]
 * is called with the [[MidiProcessor]] is closed.
 */
trait MidiProcessor extends AutoCloseable {

  private val _receiver: MidiProcessorReceiver = MidiProcessorReceiver()

  private val _transmitter: MidiProcessorTransmitter = MidiProcessorTransmitter()

  /**
   * Class used for the [[receiver]] associated with the [[MidiProcessor]]. It processes incoming MIDI messages and
   * forwards the processed ones to the receiver set for the [[transmitter]].
   */
  class MidiProcessorReceiver private[scmidi] extends Receiver {

    @volatile private var _isClosed: Boolean = false

    override def send(message: MidiMessage, timeStamp: Long): Unit = if (!_isClosed) {
      for (
        destReceiver <- transmitter.receiver;
        outputMessages = process(message, timeStamp);
        outputMessage <- outputMessages
      ) {
        destReceiver.send(outputMessage, timeStamp)
      }
    }

    /**
     * Scala idiomatic version of homonym method that ends a MIDI message and time-stamp to this receiver. If
     * time-stamping is not supported by this receiver, the time-stamp value should be -1.
     *
     * @param scMessage the MIDI message to send
     * @param timeStamp the time-stamp for the message, in microseconds
     * @return `this` instance to allow it to be used as a fluid API
     * @throws IllegalStateException if the receiver is closed
     */
    def send(scMessage: ScMidiMessage, timeStamp: Long = -1L): this.type = {
      send(scMessage.javaMidiMessage, timeStamp)
      this
    }

    override def close(): Unit = if (!_isClosed) {
      // Nothing to do for the moment. Add clean-up code here whenever necessary.

      _isClosed = true
    }

    /**
     * Checks if the receiver has been closed.
     *
     * @return True if the receiver is closed, false otherwise.
     */
    def isClosed: Boolean = _isClosed
  }

  /**
   * Class used for the [[transmitter]] associated with the [[MidiProcessor]] that provides a basic [[Transmitter]]
   * implementation accompanied by Scala idiomatic getters and setters for the output receiver. It also calls the 
   * [[onConnect()]] and [[onDisconnect()]] callbacks when the receiver is changed.
   */
  class MidiProcessorTransmitter private[scmidi] extends Transmitter, Locking {
    private implicit val lock: ReadWriteLock = ReentrantReadWriteLock()

    private var outputReceiver: Option[Receiver] = None

    @volatile private var _isClosed: Boolean = false

    override def setReceiver(value: Receiver): Unit = {
      def disconnectBeforeSet(localOutputReceiver: Option[Receiver]): Boolean = {
        if (localOutputReceiver.isDefined) {
          onDisconnect()
          true
        } else {
          false
        }
      }

      val localOutputReceiver = receiver

      if (!receiver.contains(value)) {
        val wasOnDisconnectCalled = disconnectBeforeSet(localOutputReceiver)

        withWriteLock {
          if (!wasOnDisconnectCalled) {
            disconnectBeforeSet(outputReceiver)
          }

          outputReceiver = Option(value)
        }

        onConnect()
      }
    }

    override def getReceiver: Receiver = receiver.orNull

    /**
     * Scala idiomatic version of [[Transmitter]]'s `getReceiver` method.
     *
     * @return an [[Option]] of the current receiver.
     * @see [[javax.sound.midi.Transmitter#getReceiver()]]
     */
    def receiver: Option[Receiver] = withReadLock {
      outputReceiver
    }

    /**
     * Scala idiomatic version of [[Transmitter]]'s `setReceiver` method.
     *
     * @see [[javax.sound.midi.Transmitter#setReceiver()]]
     */
    def receiver_=(value: Option[Receiver]): Unit = setReceiver(value.orNull)

    override def close(): Unit = if (!_isClosed) {
      // Nothing to do for the moment. Add clean-up code here whenever necessary.

      _isClosed = true
    }

    /**
     * Checks if the receiver has been closed.
     *
     * @return True if the receiver is closed, false otherwise.
     */
    def isClosed: Boolean = _isClosed
  }

  /**
   * @return a [[Receiver]] that can be used as input for MIDI messages which are going to be processed and forwarded
   *         to the output.
   */
  def receiver: MidiProcessorReceiver = _receiver

  /**
   * @return a [[Transmitter]] that can be used as output for MIDI messages which were received from the input and 
   *         processed.
   */
  def transmitter: MidiProcessorTransmitter = _transmitter

  /**
   * Processes a MIDI message and returns the resulting sequence of MIDI messages.
   *
   * The input messages can be filtered, modified or used to generate new MIDI output messages.
   *
   * @param message   The MIDI message to process.
   * @param timeStamp The timestamp of the MIDI message.
   * @return A sequence of processed MIDI messages.
   */
  protected def process(message: MidiMessage, timeStamp: Long): Seq[MidiMessage]

  /**
   * Callback called after a receiver is set to allow configuring the output device to be used with the processor.
   *
   * @see [[MidiProcessor#setReceiver()]]
   */
  protected def onConnect(): Unit = {}

  /**
   * Callback called before a new receiver is set to let the receiver being replaced in a consistent state.
   *
   * The processor can't know what was the exact state of the output device before connecting the processor to it.
   * Leaving it in a consistent state means setting the parameters (CCs, RPNs, NRPNs etc.) that were altered by the
   * processor to some convenient/default values.
   *
   * @see [[MidiProcessor#setReceiver()]]
   */
  protected def onDisconnect(): Unit = {}
}
