/*
 * Copyright 2025 Calin-Andrei Burloiu
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

package org.calinburloiu.music.microtonalist.tuner

import org.calinburloiu.businessync.Businessync
import org.calinburloiu.music.microtonalist.composition.OctaveTuning
import org.scalamock.scalatest.MockFactory
import org.scalatest.BeforeAndAfter
import org.scalatest.flatspec.AnyFlatSpec
import org.scalatest.matchers.should.Matchers

// TODO #95 Generated by AI. Review.
class TuningSessionTest extends AnyFlatSpec with Matchers with BeforeAndAfter with MockFactory {

  // Mocks for dependencies
  private val businessyncStub: Businessync = stub[Businessync]

  private var tuningSession: TuningSession = _

  // Sample data for testing
  private val majTuning = OctaveTuning("Just C Major",
    c = 0.0,
    cSharpOrDFlat = 0.0,
    d = 3.91,
    dSharpOrEFlat = 0.0,
    e = -13.69,
    f = -1.96,
    fSharpOrGFlat = 0.0,
    g = 1.96,
    gSharpOrAFlat = 0.0,
    a = -15.64,
    aSharpOrBFlat = 0.0,
    b = -11.73
  )
  private val rastTuning = OctaveTuning("C Rast",
    c = 0.0,
    cSharpOrDFlat = 0.0,
    d = 3.91,
    dSharpOrEFlat = 0.0,
    e = -13.69,
    f = -1.96,
    fSharpOrGFlat = 0.0,
    g = 1.96,
    gSharpOrAFlat = 0.0,
    a = 5.87,
    aSharpOrBFlat = -3.91,
    b = -11.73
  )
  // TODO #95
  private val ussakTuning = OctaveTuning("D Ussak",
    c = 0.0,
    cSharpOrDFlat = 0.0,
    d = 3.91,
    dSharpOrEFlat = 0.0,
    e = -45.45,
    f = -1.96,
    fSharpOrGFlat = 0.0,
    g = 1.96,
    gSharpOrAFlat = 0.0,
    a = 5.87,
    aSharpOrBFlat = -3.91,
    b = 0
  )

  before {
    tuningSession = new TuningSession(businessyncStub)
  }

  "TuningSession" should "initialize with empty tunings and tuningIndex set to 0" in {
    tuningSession.tunings shouldBe empty
    tuningSession.tuningIndex shouldBe 0
    tuningSession.tuningCount shouldBe 0
    tuningSession.currentTuning shouldBe OctaveTuning.Edo12
  }

  it should "set tunings" in {
    // When
    tuningSession.tunings = Seq(majTuning, rastTuning)
    // Then
    tuningSession.tunings shouldBe Seq(majTuning, rastTuning)
    tuningSession.tuningCount shouldBe 2

    // When: Setting an empty list should reset tuningIndex
    tuningSession.tunings = Seq()
    // Then
    tuningSession.tunings shouldBe empty
    tuningSession.tuningCount shouldBe 0
  }

  it should "throw an exception when setting an invalid tuningIndex" in {
    // When
    tuningSession.tunings = Seq(majTuning, rastTuning)
    // Then
    assertThrows[IllegalArgumentException] {
      tuningSession.tuningIndex = -1
    }
    assertThrows[IllegalArgumentException] {
      // Invalid index since we have only 2 tunings (0 and 1)
      tuningSession.tuningIndex = 2
    }
  }

  it should "allow setting a valid tuningIndex" in {
    // When
    tuningSession.tunings = Seq(majTuning, rastTuning, ussakTuning)
    // Then
    tuningSession.tuningIndex = 1
    tuningSession.tuningIndex shouldBe 1
    tuningSession.currentTuning shouldBe rastTuning
  }

  it should "set tunings and adjust tuningIndex if necessary" in {
    // When
    tuningSession.tunings = Seq(majTuning, rastTuning)
    // Then
    tuningSession.tunings shouldBe Seq(majTuning, rastTuning)
    // The default index should remain valid
    tuningSession.tuningIndex shouldBe 0
    tuningSession.tuningCount shouldBe 2

    // When: Adding an extra tuning
    tuningSession.tuningIndex = 1
    tuningSession.tunings = Seq(majTuning, ussakTuning, rastTuning)
    // Then: The index is maintained
    tuningSession.tunings shouldBe Seq(majTuning, ussakTuning, rastTuning)
    tuningSession.tuningIndex shouldBe 1
    tuningSession.tuningCount shouldBe 3
    tuningSession.currentTuning shouldBe ussakTuning

    // When: Removing tunings such that the count is less than the index
    tuningSession.tunings = Seq(rastTuning)
    // Then: The index is changed
    tuningSession.tuningIndex shouldBe 0

    // When: Setting an empty list should reset tuningIndex
    tuningSession.tunings = Seq()
    // Then
    tuningSession.tuningIndex shouldBe 0
    tuningSession.tuningCount shouldBe 0
    tuningSession.currentTuning shouldBe OctaveTuning.Edo12
  }

  it should "cycle to the previous and next tunings correctly" in {
    tuningSession.tunings = Seq(majTuning, rastTuning, ussakTuning)
    tuningSession.tuningIndex = 0

    // Should cycle to the last tuning
    tuningSession.previousTuning()
    tuningSession.tuningIndex shouldBe 2
    tuningSession.currentTuning shouldBe ussakTuning

    // Should cycle back to the first tuning
    tuningSession.nextTuning()
    tuningSession.tuningIndex shouldBe 0
    tuningSession.currentTuning shouldBe majTuning
  }

  it should "publish TuningChangedEvent when tunings are set" in {
    // When
    tuningSession.tunings = Seq(majTuning, rastTuning)
    // Setting it twice
    tuningSession.tunings = Seq(majTuning, rastTuning)
    // Then
    businessyncStub.publish _ verify TuningChangedEvent(majTuning, 0, 0) once
  }

  it should "publish TuningChangedEvent when tuningIndex changes" in {
    // Given
    tuningSession.tunings = Seq(majTuning, rastTuning)
    val oldTuningIndex = tuningSession.tuningIndex
    // When
    tuningSession.tuningIndex = 1 // Set a new index
    // Then
    businessyncStub.publish _ verify TuningChangedEvent(rastTuning, 1, oldTuningIndex)
  }

  it should "not publish TuningChangedEvent when tuningIndex remains the same" in {
    // Given
    tuningSession.tunings = Seq(majTuning, rastTuning)
    // When
    tuningSession.tuningIndex = 0 // Setting the same index
    // Then
    businessyncStub.publish _ verify * once
  }
}